### ISSUE TITLE
Xcode 12.4 is complaining about iOS8 compatibility

### ISSUE THREAD

**Issue by megakoko** [noahsark769/ColorCompatibility#10]
I'm using ColorCompatibility as a SPM package with Xcode 12.4 (12D4e) and it produces a warning message in the project:

> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99.

Thank you for really useful framework!

**Comment by noahsark769** [comment]
Ah, you're right! I think this is because we're specifying `.v8` in the `Package.swift`. If you'd like to submit a pull request to update that to v9 and bump the version I'd be happy to accept it, otherwise I can probably update it at some point relatively. Thanks for pointing this out!

**Comment by megakoko** [comment]
@noahsark769 

Hello Noah, 

I've just submitted a pull request to fix the warning. I've bumped the framework version to 1.2.0. If you want me to change it to other version — let me know. 

Thanks

**Comment by megakoko** [comment]
Hello Noah,

Have you had a chance to have a look at the pull request?

Cheers,

Andy

**Comment by noahsark769** [comment]
Gosh, sorry for the delay here! Thanks for the change, I've merged that pull request. Appreciate it!
