### ISSUE TITLE
Missing .systemGray

### ISSUE THREAD

**Issue by johnclayton** [noahsark769/ColorCompatibility#2]
It's present in your writeup, but not in the enum.

**Comment by johnclayton** [comment]
your write up has them in the table correctly, but the enum is missing a lot of colors, amongst them .systemGray and all the primary colors (red, yellow, green, ...)

**Comment by noahsark769** [comment]
See comment on #3 - this is because these colors were not introduced in iOS 13.

**Comment by noahsark769** [comment]
Closed this based on the comment in #3. Thanks!
