### ISSUE TITLE
"Elevated" colors can be different

### ISSUE THREAD

**Issue by michaellenaghan** [noahsark769/ColorCompatibility#7]
Just to make sure you're aware: "elevated" dark colors can be [different](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode/), e.g.:

> Dark Mode is dynamic, which means that the background color automatically changes from base to elevated when an interface is in the foreground, such as a popover or modal sheet. The system also uses the elevated background color to provide visual separation between apps in a multitasking environment and between windows in a multiple-window context. Using a custom background color can make it harder for people to perceive these system-provided visual distinctions.

There are screenshots below that demonstrating the change, but on a light page the screenshots don't really convey the difference very well.

**Comment by michaellenaghan** [comment]
I think these are the base / elevated colors (which, I believe, only apply to dark mode):

// .systemBackground: #000000FF rgba(0, 0, 0, 1.00) / #1C1C1E rgba(28, 28, 30, 1.00)
// .secondarySystemBackground: #1C1C1E rgba(28, 28, 30, 1.00) / #2C2C2EFF rgba(44, 44, 46, 1.00)
// .tertiarySystemBackground: #2C2C2EFF rgba(44, 44, 46, 1.00) / #3A3A3C rgba(58, 58, 60, 1.00)

// .systemGroupedBackground:  #000000FF rgba(0, 0, 0, 1.00) / #1C1C1E rgba(28, 28, 30, 1.00)
// .secondarySystemGroupedBackground: #1C1C1EFF rgba(28, 28, 30, 1.00) / #2C2C2EFF rgba(44, 44, 46, 1.00)
// .tertiarySystemGroupedBackground: #2C2C2EFF rgba(44, 44, 46, 1.00) / #3A3A3C rgba(58, 58, 60, 1.00)

As you can see, each elevated color is just the next base color — i.e., the elevated `.systemBackground` color is the base `.secondarySystemBackground` color.

I don't know if any of this is helpful for backward compatibility, which is the purpose of your library. Still, good to know about if you weren't aware. For some undefined "you". :-)

**Comment by noahsark769** [comment]
Sure, thank you for this! Since this library is for backwards compatibility, I'm not sure there need to be any code changes here, but I'll add something to the README to document that this is the case. Thanks for bringing it up!

**Comment by noahsark769** [comment]
I've added some documentation to the readme about this in 14602f93e42487b74a69cfb9b17a9575bdbcd760. Feel free to suggest anything further if you think it's necessary! Thank you!
